name: Bug report
description: Incorrect verification result or verifier malfunction
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual
      description: Include exact error text.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser + OS
    validations:
      required: true